### ISSUE TITLE
PROJ_NETWORK=OFF

### ISSUE THREAD

**Issue by snowman2** [conda-forge/proj-data-feedstock#4]
I think if `proj-data` is installed, it should disable the network since it is no longer needed. Also, the logic for the existence of this package is that users cannot (or don't wish to) use `projsync` as the users are unable to download via the CDN.

Does this logic make sense to y'all?

**Comment by xylar** [comment]
@snowman2, that sounds reasonable but challenging.  The `PROJ_NETWORK` environment variable is set in the activate/deactivate scripts of `proj`, not this package.  If we were to try to set it from this package, too, my understanding is that we don't know which activate/deactivate script would get called first when we activate the environment.  So it wouldn't be safe to try to manipulate the same variable here.

So the question is, how would `proj` know in its activate script whether `proj-data` is installed or not?

**Comment by xylar** [comment]
closed via https://github.com/conda-forge/proj.4-feedstock/pull/73
